# Generated by Django 6.0.6 on 2026-06-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_alter_click_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='expiration_date',
        ),
        migrations.AlterField(
            model_name='url',
            name='short_code',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
